#!/usr/bin/env python3
"""Regenerate the parity fixture: what the Python model says on fixed inputs.

The model is implemented twice -- model/fit.py is the reference, and the
JavaScript in web/app.html is a hand-port so the page stays dependency-free.
tests/parity.spec.js runs the JS half on these same inputs and checks it agrees.

Deterministic quantities (the time-constant prior, the curve, time-to-target)
are compared exactly; posterior summaries are compared within a band, because
the two use different samplers and different PRNGs.

    python3 tools/parity.py            # print the fixture
    python3 tools/parity.py --write    # write tests/fixtures/parity.json
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "model"))

from fit import advise, default_priors, fit, geometry_from_mass, predict, tau_prior_minutes  # noqa: E402

# Fixed inputs both implementations are asked about.
CASES = [
    {"name": "cold start, three readings", "ts": [0.0, 20.0, 30.0], "temps": [5.0, 18.8, 29.0], "now": 30.0},
    {"name": "two readings, early", "ts": [0.0, 14.0], "temps": [5.0, 12.0], "now": 14.0},
    {"name": "nearly there", "ts": [0.0, 18.0, 30.0, 38.0], "temps": [5.0, 22.0, 34.0, 40.0], "now": 38.0},
    {"name": "stalling", "ts": [0.0, 15.0, 30.0, 45.0], "temps": [5.0, 26.0, 35.0, 38.5], "now": 45.0},
]

GEOMETRIES = [
    {"mass": 1.0, "thick": 0.040, "fan": False},
    {"mass": 1.0, "thick": 0.055, "fan": False},
    {"mass": 0.6, "thick": 0.030, "fan": True},
    {"mass": 1.4, "thick": 0.050, "fan": True},
]

CURVE = {"log_tau": math.log(55.0), "t_inf": 100.0, "lag": 7.0, "t0": 5.0}


def build() -> dict:
    out = {
        "note": "Generated by tools/parity.py from model/fit.py. Do not edit by hand.",
        "tau_prior": [],
        "curve": {**CURVE, "at": {}},
        "time_to": {},
        "cases": [],
    }

    for g in GEOMETRIES:
        w, l = geometry_from_mass(g["mass"], g["thick"])
        h = 26.0 if g["fan"] else 20.0
        out["tau_prior"].append({
            "mass": g["mass"], "thickMm": g["thick"] * 1000, "fan": g["fan"],
            "width": w, "length": l,
            "tau": tau_prior_minutes(g["thick"], w, l, h=h),
        })

    theta = np.array([[CURVE["log_tau"], CURVE["t_inf"], CURVE["lag"], CURVE["t0"]]])
    for t in (0.0, 5.0, 7.0, 15.0, 30.0, 60.0, 120.0):
        out["curve"]["at"][str(t)] = float(predict(theta, np.array([t]))[0, 0])

    post = fit([0.0], [5.0], default_priors(1.0, 0.040, 125.0), seed=1)
    post.samples = np.array([[CURVE["log_tau"], CURVE["t_inf"], CURVE["lag"], CURVE["t0"]]])
    for target in (30.0, 44.0, 99.0, 105.0):
        v = float(post.time_to(target)[0])
        out["time_to"][str(target)] = None if math.isinf(v) else v

    for c in CASES:
        pr = default_priors(1.0, 0.040, 125.0)
        p = fit(c["ts"], c["temps"], pr, seed=20240501)
        a = advise(p, c["now"], 44.0)
        hits = p.time_to(44.0)
        finite = hits[np.isfinite(hits)]
        out["cases"].append({
            "name": c["name"],
            "ts": c["ts"], "temps": c["temps"], "now": c["now"],
            "tau_median": float(np.median(np.exp(p.samples[:, 0]))),
            "t_inf_median": float(np.median(p.samples[:, 1])),
            "temp_now_median": float(np.median(p.temp_at(c["now"])[:, 0])),
            "hit_p05": float(np.percentile(finite, 5)) if len(finite) else None,
            "hit_median": float(np.percentile(finite, 50)) if len(finite) else None,
            "hit_p95": float(np.percentile(finite, 95)) if len(finite) else None,
            "stall": float(a.stall_risk),
            "action": a.action,
            # NOTE the deliberate asymmetry: for a "coast" the JS puts the pull
            # time in `next` (the card counts down to it), while Python keeps
            # the unused safe-check time in next_check_min and the pull in
            # pull_min. Compare `pull` for coast, `next` for measure.
            "next_check": float(a.next_check_min),
            "pull": float(a.pull_min),
        })
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="write tests/fixtures/parity.json")
    args = ap.parse_args()

    data = build()
    text = json.dumps(data, indent=2) + "\n"
    if args.write:
        path = os.path.join(ROOT, "tests", "fixtures", "parity.json")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(text)
        print(f"wrote {path}")
    else:
        print(text)


if __name__ == "__main__":
    main()
